[signals::signal_signature_test]
    linux
    darwin
    win32
[Qt3DExtras::qt3dextras_test]
    win32 ci
    linux
    darwin
[QtMultimedia::audio_test]
    linux
    darwin
    win32
# PYSIDE-474
[QtWebEngineWidgets::pyside-474-qtwebengineview]
    py2
    py3
[QtCore::qthread_test]
    linux py3.6
# PYSIDE-754
[QtWebEngineCore::web_engine_custom_scheme]
    win32
    linux
    darwin
# In addition to a pre-existing windows failure,
# qtlocation/ac899dcc40bb3ad09307583fb7e6befd45a77b33 / QTBUG-66304 introduced
# a failure in 5.14
[QtPositioning::positioning]
    win32
    linux
    darwin
# Open GL functions failures on macOS (2/2020)
[registry::existence_test]
    darwin
[QtQml::qqmlnetwork_test]
    linux ci    # extended, see PyPy section
[QtWidgets::bug_750]
    darwin ci
[QtWidgets::qpicture_test]
    darwin ci
# Unsolved Refcounting leaks in debug mode
[pysidetest::property_python_test]
    debug
[signals::bug_79]
    debug

# PYSIDE-535: These errors are still present. Please try to remove one :)
[sample::mixed_mi]
    pypy
[sample::ownership_invalidate_child]
    pypy
[sample::renaming]
    pypy
[sample::sample]
    pypy
[sample::str]
    pypy
[sample::typedealloc]
    pypy
[smart::smart_pointer]
    pypy
[pysidetest::constructor_properties_test]
    pypy
[pysidetest::homonymoussignalandmethod_test]
    pypy
[pysidetest::mixin_signal_slots_test]
    pypy
[signals::qobject_destroyed_test]
    pypy
[signals::qobject_receivers_test]
    pypy
[signals::qobject_sender_test]
    pypy
[QtCore::classinfo_test]
    pypy
[QtCore::destroysignal_test]
    pypy
[QtCore::qbytearray_test]
    pypy
[QtCore::qeasingcurve_test]
    pypy
[QtCore::qobject_inherits_test]
    pypy
[QtCore::qproperty_decorator]
    pypy
[QtWidgets::action_clear]
    pypy
[QtWidgets::bug_836]
    pypy
[QtWidgets::bug_860]
    pypy
[QtWidgets::qlayout_test]
    pypy
[QtWidgets::signature_test]
    pypy
[QtQml::bug_825]
    pypy
[QtQml::qqmlnetwork_test]
    pypy
    linux ci    # from above
[QtQml::javascript_exceptions]
    pypy
# 2022-03-04 PyPy: Currently 27 of 657 tests fail
